{{- if not .Values.splunk.existingSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "splunk.secret.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
  {{- range $key, $value := .Values.extraLabels }}
    {{ $key }}: {{ $value }}
  {{- end }}
type: Opaque
data:
  access-token: {{ .Values.splunk.accessToken | b64enc | quote }}
  api-base-url: {{ .Values.splunk.apiBaseUrl| b64enc | quote }}
{{- end }}
